{% set name = "langchain-community" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: bfb3f2b219aed21087e0ecb7d2ebd1c81401c02b92239e11645c822d5be63f80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - langchain <0.4.0,>=0.3.4
    - python >=3.8.1,<4.0
    - langchain-core <0.4.0,>=0.3.1
    - sqlalchemy >=1.4,<3
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.0.0,<2.0.0
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,<9.0.0
    - dataclasses-json >=0.5.7,<0.7
    - pydantic-settings >=2.4.0,<3.0.0
    - langsmith >=0.1.112,<0.2.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - jan-janssen
