{% set name = "langchain-community" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: 8abe05b4ab160018dbd368f7b4dc79ef6a66178a461b47c4ce401d430337e0c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - langchain <0.4.0,>=0.3.11
    - python >={{ python_min }}
    - langchain-core <0.4.0,>=0.3.24
    - sqlalchemy <2.0.36,>=1.4
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.0.0,<2.0.0
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,<9.0.0
    - dataclasses-json >=0.5.7,<0.7
    - pydantic-settings >=2.4.0,<3.0.0
    - langsmith >=0.1.112,<0.2.0
    - httpx-sse

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - jan-janssen
