{% set name = "langchain-community" %}
{% set version = "0.3.22" %}
{% set build = 0 %}
{% set python_max = ",<3.12a0" if python_min == "3.9" else "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: 36284687a9f64bc7820c0140beb3b96393f6c74c0b7ad8ba04ac35d673fe0988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}
  string: "pymin{{ python_min|replace('.', '') }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - langchain <1.0.0,>=0.3.24
    - python >={{ python_min }}{{ python_max }}
    - langchain-core <1.0.0,>=0.3.55
    - sqlalchemy <3,>=1.4
    - requests <3,>=2
    - pyyaml >=5.3
    {% if python_max == "" %}
    - numpy >=1.26.2
    {% else %}
    - numpy >=1.22.4,<2
    {% endif %}
    - aiohttp <4.0.0,>=3.8.3
    - tenacity !=8.4.0,<10,>=8.1.0
    - dataclasses-json <0.7,>=0.5.7
    - pydantic-settings <3.0.0,>=2.4.0
    - langsmith <0.4,>=0.1.125
    - httpx-sse <1.0.0,>=0.4.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - jan-janssen
