{% set name = "langchain-community" %}
{% set version = "0.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: d8ba0fe2dbb5795bff707684b712baa5ee379227194610af415ccdfdefda0479

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - langchain >=0.3.14,<0.4.0
    - python >={{ python_min }}
    - langchain-core >=0.3.29,<0.4.0
    - sqlalchemy >=1.4,<3
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    - numpy >=1.22.4,<2
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,!=8.4.0,<10
    - dataclasses-json >=0.5.7,<0.7
    - pydantic-settings >=2.4.0,<3.0.0
    - langsmith >=0.1.125,<0.3
    - httpx-sse >=0.4.0,<0.5.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - jan-janssen
