{% set name = "langchain-community" %}
{% set version = "0.3.16" %}
{% set build = "1" %}
{% set python_max = ",<3.12a0" if python_min == "3.9" else "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: 825709bc328e294942b045d0b7f55053e8e88f7f943576306d778cf56417126c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}
  string: "pymin{{ python_min|replace('.', '') }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - langchain >=0.3.16,<0.4.0
    - python >={{ python_min }}{{ python_max }}
    - langchain-core >=0.3.32,<0.4.0
    - sqlalchemy >=1.4,<3
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3
    {% if python_max == "" %}
    - numpy >=1.22.4,<3
    {% else %}
    - numpy >=1.22.4,<2
    {% endif %}
    - aiohttp >=3.8.3,<4.0.0
    - tenacity >=8.1.0,!=8.4.0,<10
    - dataclasses-json >=0.5.7,<0.7
    - pydantic-settings >=2.4.0,<3.0.0
    - langsmith >=0.1.125,<0.4
    - httpx-sse >=0.4.0,<0.5.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - efriis
    - agola11
    - jan-janssen
