{% set name = "langchain-community" %}
{% set version = "0.4" %}
{% set build = 0 %}
{% set python_max = ",<3.12a0" if python_min == "3.10" else "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_community-{{ version }}.tar.gz
  sha256: 11ff08c3d923641cecbe17379cfeeb1258eed1b51bbf1784362d69bb5fe38bf2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build }}
  string: "pymin{{ python_min|replace('.', '') }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - langchain-classic >=1.0.0,<2.0.0
    - langchain >=0.3.27,<2.0.0
    - python >={{ python_min }}{{ python_max }}
    - langchain-core >=1.0.0,<2.0.0
    - sqlalchemy >=1.4.0,<3.0.0
    - requests >=2.32.5,<3.0.0
    - pyyaml >=5.3.0,<7.0.0
    {% if python_max == "" %}
    - numpy >=1.26.2
    {% else %}
    - numpy >=1.22.4,<2
    {% endif %}
    - aiohttp >=3.8.3,<4.0.0
    - tenacity !=8.4.0,>=8.1.0,<10.0.0
    - dataclasses-json >=0.6.7,<0.7.0
    - pydantic-settings >=2.10.1,<3.0.0
    - langsmith >=0.1.125,<1.0.0
    - httpx-sse >=0.4.0,<1.0.0

test:
  imports:
    - langchain_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: Community contributed LangChain integrations.
  doc_url: https://api.python.langchain.com/en/stable/community_api_reference.html
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/community
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dlqqq
    - 3coins
    - pavelzw
    - hinthornw
    - baskaryan
    - hwchase17
    - ccurme
    - sydney-runkle
    - agola11
    - jan-janssen
